pipeline{
  agent any

  environment{
    DOCKERHUB_CREDENTIALS=credentials('dockerid')
    IMAGE_NAME="Darshan/webapp"
  }
  stages
  {
    stage('checkout')
    {
      steps{
        git(url:"https://github.com/usn1ms24mc023/first_project",branch:"main",credentialsId:"dockerid")
      }
   }
    stage('Build')
    {
      steps{
        script{
          dockerImage=docker.build("${IMAGE_NAME}:latest)
        }
      }
    }
    stage('push')
  {
    steps{
      script{
      docker.withRegistry('https://index.docker.io/v1/','dockerid'){
        dockerImage.push()
      }
      }
    }
  }
  }
}
